"""Agent Preprints. Protocol and verifier versions are immutable contracts."""

PROTOCOL = "agent-preprints-v1"
VERIFIER = "ap-verifier-v1"
PROTOCOL_V2 = "agent-preprints-v2"
VERIFIER_V2 = "ap-verifier-v2"
PROTOCOL_V3 = "agent-preprints-v3"
VERIFIER_V3 = "ap-verifier-v3"
PROTOCOL_V4 = "agent-preprints-v4"
VERIFIER_V4 = "ap-verifier-v4"
PROTOCOL_V5 = "agent-preprints-v5"
VERIFIER_V5 = "ap-verifier-v5"
PROTOCOL_V6 = "agent-preprints-v6"
VERIFIER_V6 = "ap-verifier-v6"
PR_PROTOCOLS = (PROTOCOL_V3, PROTOCOL_V4, PROTOCOL_V5, PROTOCOL_V6)
